In [1]:
import numpy as np

In [2]:
#Beispielarray definieren:
#shape numpy array ist tupel

In [9]:
a=np.zeros((10,8,6))

In [7]:
a[0][0][0] #axe 0,1,2

0.0

In [10]:
shape=a.shape

In [11]:
for i in range(shape[0]):
    for j in range(shape[1]):
        for m in range(shape[2]):
            a[i][j][m]=i+j+m

In [13]:
#a

In [14]:
a[4][3][1] #grün

8.0

In [19]:
a[:][3]#[:]

array([[ 3.,  4.,  5.,  6.,  7.,  8.],
       [ 4.,  5.,  6.,  7.,  8.,  9.],
       [ 5.,  6.,  7.,  8.,  9., 10.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [ 8.,  9., 10., 11., 12., 13.],
       [ 9., 10., 11., 12., 13., 14.],
       [10., 11., 12., 13., 14., 15.]])

In [23]:
a[:][4][3]

array([ 7.,  8.,  9., 10., 11., 12.])

In [28]:
a[4][:][3]

array([ 7.,  8.,  9., 10., 11., 12.])

In [25]:
#durch zufall gleich jojo

In [29]:
#numpy unterscheidet nicht zw zilen und spalten vektor er transponiert nicht selbst

In [41]:
a[2:4]#[1:7]#[1:2]

array([[[ 2.,  3.,  4.,  5.,  6.,  7.],
        [ 3.,  4.,  5.,  6.,  7.,  8.],
        [ 4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  6.,  7.,  8.,  9., 10.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [ 8.,  9., 10., 11., 12., 13.],
        [ 9., 10., 11., 12., 13., 14.]],

       [[ 3.,  4.,  5.,  6.,  7.,  8.],
        [ 4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  6.,  7.,  8.,  9., 10.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [ 8.,  9., 10., 11., 12., 13.],
        [ 9., 10., 11., 12., 13., 14.],
        [10., 11., 12., 13., 14., 15.]]])

In [42]:
a[2:4,1:7,1:2]

array([[[ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]],

       [[ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]]])

In [ ]:
#concatenate dann um wieder rgb listen herzustellen 2nd axis
#wenn man sie vorher trennte
